name: FloorPlanGen
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - scipy
  - transformers>=4.42
  - datasets
  - tokenizers
  - pytorch
  - accelerate>=0.26.0
