from .coverage import CoverageTest
from .parsability_rate import ParsabilityRate
from .geometry_validity import GeomValidityRate
from .rooms_overlapping import RoomsOverlappingTest
from .base_metrics import BaseMetrics
from .required_rooms import RequiredRoomsTest
from .narrow_spaces import NarrowSpacesTest
from .geometry_simplicity import GeometrySimplicityTest
from .rooms_neighborhood import RoomsNeighborhoodTest
