general:
  seed: 42

model:
  with_xy_indices: True
  with_corner_indices: True
  max_seq_len: 320
  n_layer: 25
  n_head: 16
  n_embd: 256   # embedding and hidden states dimension

training:
  input_data: "./data/gpt2_main/input/"
  epochs: 60
  lr: 1e-5
  batch_size: 32
  eval_steps: 500
  log_comment: "_25_layers_training"
  checkpointing_frequency: 5  # checkpoint every n epochs
