general:
  seed: 42

paths:
  input_data: "./data/input"
  output_data: "./data/output"
  trained_model: "./models/custom/"

preprocessing:
  test_size: 0.05
  validate_size: 0.005
  data_augmentation:
    - permutation:
        percentage: 0.4
    - symmetry:
        percentage: 0.4
    - rotation:
        percentage: 0.4

model:
  name: "custom_model"
  type: "gemma3"
  max_seq_len: 320
  hidden_size: 256         # embedding dim
  sliding_window: 100
  intermediate_size: 1024

training:
  loop_type: "custom"
  epochs: 20
  lr: 1e-5
  batch_size: 32
  eval_steps: 500
  log_comment: "_custom_training"

