general:
  seed: 42

paths:
  input_data: "./data/gpt2_main/input/"

preprocessing:
  test_size: 0.05
  validate_size: 0.005
  data_augmentation:
    - permutation:
        percentage: 0.4
    - symmetry:
        percentage: 0.4
    - rotation:
        percentage: 0.4

model:
  name: "gpt2_with_xy_indices"
  type: "gpt2"
  with_coord_indices: True
  max_seq_len: 320
  n_layer: 12
  n_head: 8
  n_embd: 256

training:
  loop_type: "custom"
  epochs: 60
  lr: 1e-5
  batch_size: 32
  eval_steps: 500
  log_comment: "_xy_indices_training"
