general:
  seed: 42

preprocessing:
  test_size: 0.05
  validate_size: 0.005
  data_augmentation:
    - permutation:
        percentage: 0.4
    - symmetry:
        percentage: 0.4
    - rotation:
        percentage: 0.4

model:
  input_model_path: "runs/2026-01-06-13:57:53_fast_test_training"
  max_seq_len: 320

training:
  input_data: "./data/gpt2_fast_test/input"
  epochs: 10
  lr: 1e-4
  batch_size: 32
  eval_steps: 2
  checkpointing_frequency: 3  # checkpoint every n epochs
  log_comment: "_fast_test_training"
  lr_scheduler:
    type: "cyclic"
    base_lr: 1e-8
    max_lr: 1e-4
    cycles: 3
