general:
  seed: 42

paths:
  input_data: "./data/gpt2_fast_test/input"

preprocessing:
  test_size: 0.05
  validate_size: 0.005
  data_augmentation:
    - permutation:
        percentage: 0.4
    - symmetry:
        percentage: 0.4
    - rotation:
        percentage: 0.4

model:
  input_model_path: "2025-12-15-21:30:06_fast_test_training"
  # from_checkpoint: True
  # checkpoint_epoch: 9
  max_seq_len: 320

training:
  loop_type: "custom"
  epochs: 10
  lr: 1e-5
  batch_size: 32
  eval_steps: 500
  log_comment: "_main_gpt2_continue_training_with_coords"
  checkpointing_frequency: 3  # checkpoint every n epochs
