general:
  seed: 42

paths:
  input_data: "./data/input"
  output_data: "./data/output"
  trained_model: "./models/"

preprocessing:
  test_size: 0.05
  validate_size: 0.005
  data_augmentation:
    - permutation:
        percentage: 0.4
    - symmetry:
        percentage: 0.4
    - rotation:
        percentage: 0.4

model:
  model_name: "main_model"
  max_seq_len: 320

training:
  epochs: 150
  lr: 1e-5
  batch_size: 32
  eval_steps: 500
  log_comment: "_main_training"

